# Generated by Django 6.0.4 on 2026-04-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_category_remove_category_description_and_more'),
        ('orders', '0002_rename_created_at_order_create_remove_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
